# Generated by Django 3.1.6 on 2021-05-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created', models.DateField()),
                ('country', models.CharField(max_length=64)),
                ('league', models.CharField(max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, unique=True)),
                ('amount', models.CharField(blank=True, max_length=64, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football_club.club')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football_club.club')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
                ('created', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football_club.club')),
            ],
        ),
    ]
