# Generated by Django 3.2.3 on 2021-06-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_club', '0004_alter_club_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trophy',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
