# Generated by Django 3.2.3 on 2021-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_club', '0006_auto_20210604_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='amount',
        ),
        migrations.AddField(
            model_name='club',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='staff',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
