# Generated by Django 3.2.3 on 2021-06-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_club', '0007_auto_20210608_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='trophylist',
            field=models.TextField(blank=True, null=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='stadium',
            name='bestgames',
            field=models.TextField(blank=True, null=True, verbose_name='Лучшие матчи'),
        ),
        migrations.AddField(
            model_name='staff',
            name='trophylist',
            field=models.TextField(blank=True, null=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='trophy',
            name='actual_owner',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trophy',
            name='created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trophy',
            name='recordsman',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trophy',
            name='winers',
            field=models.TextField(blank=True, null=True, verbose_name='Список обладателей'),
        ),
        migrations.AlterField(
            model_name='club',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
