# Generated by Django 3.2.3 on 2021-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_club', '0008_auto_20210608_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='teams_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
