# Generated by Django 3.1.6 on 2021-06-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_club', '0009_club_teams_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['second_name']},
        ),
        migrations.AlterModelOptions(
            name='trophy',
            options={'ordering': ['name']},
        ),
    ]
